Create house model example for Romenys Framework
romenys/romenys pull request #6
Opened 2017-01-30 16:13 UTC by anzouaoui

2017-01-30 23:56 UTC, khalid-s requested changes
Corrige aussi tout les EOF et ping moi

2017-01-30 23:56 UTC, khalid-s commented on src/PropertiesBundle/Entity/House.php
> +	/**
mauvaise indentation

2017-01-31 09:13 UTC, anzouaoui commented
@khalid-s

2017-01-31 10:29 UTC, khalid-s approved these changes

2017-01-31 10:31 UTC, merged